before_script:
   - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
   - sudo apt-get -qq update
   - sudo apt-get install build-essential libboost-all-dev git libfftw3-dev autoconf cmake libprotobuf-dev python-protobuf python-qt4-gl python-yaml protobuf-compiler protobuf-c-compiler python-qt4 python-qt4-dev pyqt4-dev-tools python-matplotlib python-setuptools python-qwt5-qt4 libqwt-dev libyaml-cpp-dev libzmq-dev libzmq3-dev
language: cpp
script:
 - mkdir build
 - cd build
 - cmake ..
 - make

# watch master and next branches only
branches:
 only:
   - projectrestruct
