before_script:
   - sudo apt-get -qq update
   - sudo apt-get install build-essential libboost-all-dev git libfftw3-dev autoconf cmake libprotobuf-dev python-protobuf python-qt4-gl python-yaml protobuf-compiler protobuf-c-compiler python-qt4 python-qt4-dev pyqt4-dev-tools python-matplotlib python-setuptools python-qwt5-qt4 libzmq-dev libzmq3-dev libpgm-dev python-zmq libqwt-dev

language: cpp
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - sudo make install

# watch master and next branches only
branches:
 only:
   - master
   - next
