#
# SYSTEM CONFIGURATION FILE
# #########################
#
# purpose: definition of intercomponent communication relations
# 


#
# component definitions:
# - each component needs to define:
#    - its name
#    -  a list of gates
# - every gate consists of a name mapped to a type 
#   [pub, sub, req, rep]
#

components:

   - name: pySysMoCo
     gates:
      - fastSensingResult: sub
#      - fineSensingResult: sub
#      - chStatusUpdate: sub

   - name: examplePublisher
     gates:
      - fastSensingResult: pub

#
# component connections (component_a.gate_x -- component_b.gate_y)
#

connections:

   - [ pySysMoCo.fastSensingResult,   examplePublisher.fastSensingResult ]
