#
# SYSTEM CONFIGURATION FILE
# #########################
#
# purpose: definition of intercomponent communication relations
# 


#
# component definitions:
# - each component needs to define:
#    - its name
#    -  a list of gates
# - every gate consists of a name mapped to a type 
#   [pub, sub, req, rep]
#

components:

   - name: pySysMoCo
     gates:
      - fastSensingResult: sub
      - fineSensingResult: sub
      - chStatusUpdate: sub
      - qosRequirements: sub
      - linkStatistics: sub

   - name: examplePublisher
     gates:
      - fastSensingResult: pub
      
   - name: FftSensingController
     gates:
      - fineSensingResult: pub
      - chStatusUpdate: pub

   - name: TrafficAnalyzerComponent
     gates:
      - qosRequirements: pub
      - linkStatistics: pub
 

#
# component connections (component_a.gate_x -- component_b.gate_y)
#

connections:

   - [ pySysMoCo.fastSensingResult,   examplePublisher.fastSensingResult ]
   - [ pySysMoCo.fineSensingResult,   FftSensingController.fineSensingResult ]
   - [ pySysMoCo.chStatusUpdate,      FftSensingController.chStatusUpdate ]
   - [ pySysMoCo.qosRequirements,     TrafficAnalyzerComponent.qosRequirements ]
   - [ pySysMoCo.linkStatistics,      TrafficAnalyzerComponent.linkStatistics ]
