# to find libmessages.so and python protobuf files
export PATH=$PATH:$MOBICOM_PATH/$MOBICOM_PROJECT_NAME/common/scripts
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MOBICOM_PROJECT_BUILD_PATH/common/message-defs
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MOBICOM_PATH/$MOBICOM_BUILD_NAME/common/scl/src
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export PYTHONPATH=$PYTHONPATH:$MOBICOM_PROJECT_BUILD_PATH/common/message-defs
