#
# SYSTEM CONFIGURATION FILE
# #########################
#
# purpose: definition of intercomponent communication relations
# 


#
# component definitions:
# - each component needs to define:
#    - its name
#    -  a list of gates
# - every gate consists of a name mapped to a type 
#   [pub, sub, req, rep]
#

components:

   - name: pySysMoCo
     gates:
      - phyevent: sub
      - linklayerevent: sub
      - appevent: sub
      - drmevent: sub
      - radioconfcontrol: req
      - drmclientdata: sub
      
   - name: drm
     gates:
      - control: rep
      - data: sub
      - event: pub

   - name: drmclient
     gates:
      - control: req
      - data: pub
      - event: sub

   - name: ExampleModule
     gates:
      - phyevent: sub

   - name: RadioConfigController
     gates:
      - control: rep

   # This is a abstract name for PHY layer component
   # such as a sensing block or demodulator
   - name: PhyComponent
     gates:
      - event: pub

   - name: LinkLayerComponent
     gates:
      - event: pub

   - name: AppComponent
     gates:
      - event: pub

#
# component connections (component_a.gate_x -- component_b.gate_y)
#

connections:

   - [ pySysMoCo.phyevent,            PhyComponent.event ]
   - [ pySysMoCo.linklayerevent,      LinkLayerComponent.event ]
   - [ pySysMoCo.appevent,            AppComponent.event ]
   - [ pySysMoCo.drmevent,            drm.event ]
   - [ pySysMoCo.drmclientdata,       drmclient.data ]
   - [ pySysMoCo.radioconfcontrol,    RadioConfigController.control ]
   - [ ExampleModule.phyevent,        PhyComponent.event ]
   - [ drmclient.control,             drm.control ]
   - [ drmclient.data,                drm.data ]
   - [ drm.event,                     drmclient.event ]
